export const STUDIO_LANGUAGES = [
  { value: "", label: "Detect language" },
  { value: "en-US", label: "English (US)" },
  { value: "en-GB", label: "English (UK)" },
  { value: "fa-IR", label: "Persian" },
  { value: "es-US", label: "Spanish" },
  { value: "fr-FR", label: "French" },
  { value: "de-DE", label: "German" },
  { value: "it-IT", label: "Italian" },
  { value: "pt-BR", label: "Portuguese" },
  { value: "tr-TR", label: "Turkish" },
  { value: "ar-EG", label: "Arabic" },
  { value: "hi-IN", label: "Hindi" },
  { value: "ja-JP", label: "Japanese" },
  { value: "ko-KR", label: "Korean" },
  { value: "cmn-Hans-CN", label: "Chinese" },
  { value: "ru-RU", label: "Russian" },
] as const;
